### PR TITLE
Steps to rewrite YT convert script

### LINKED ISSUE #143: Review YT python script
Question: why is the playlist result trimmed at max 25?

```python
playlist_url = "/playlists/?maxResults=25&id={}&part=snippet%2CcontentDetails&key={}".format(
    playlist_id, API_KEY
)
```

### PR DESCRIPTION
**Pull request by razcore-art**
So this isn't ready, it's a WIP, but I'm making good progress. So what's happening? Oh, by the way, pretty nice idea on that `Pipfile` stuff, makes installs easier when collaborating.

So, the new dependencies are:
```
python-youtube = "*"
python-dotenv = "*"
dataclasses-json = "*"
```

I found a module that abstracts away all the YT low-level interaction so we're moving there.

- changed the name to: `ytplaylist-converter`. I know you like your long names, but it just didn't sound good to me :P 
- and the py file is now `ytplaylist-to-pages.py`
- had to make a "manual" addition to `python-youtube` and that's what `utils.py` is for - to make a function to get all the videos from a playlist, the module has a hard limit by google's limit of `maxRequests` (to 50)
- moved configuration in `config.py` and removed the `API_KEY` (you should never store this in a public repo). So what's the way to use your key then? Just make a `.env` file with this:

```sh
YT_API_KEY=SUPER_SECRET_YT_API_KEY
```

- move used playlist ids to `history.json` - we'll use json to keep track of cached playlists
- rewrote some functions a bit
- for now only output the series `_index.md` file

Left to do:
- [x] output leaf files for videos
- [x] output chapter `_index.md` file so that we can use `.Pages` in `hugo`
- [x] incorporate other info such as video duration and anything else.

Closes #143

### CODE REVIEW

**Comment by NathanLovato** [comment]
The API key was in clear in the repo? I didn't pay attention at the time. We'll have to rewrite the git history then.

**Comment by razcore-art** [comment]
@NathanLovato just revoke & generate a new Google API, no need to complicate stuff with rewriting history. It's all good now, just follow the instructions to make that `.env` file (which is added in `.gitignore`)

**Comment by NathanLovato** [comment]
After installing the dependencies, I'm getting the following error:

```py
Traceback (most recent call last):
  File "ytplaylist-to-pages.py", line 122, in <module>
    main()
  File "ytplaylist-to-pages.py", line 84, in main
    playlist_id=args.playlist, parts=["snippet"], count=None
  File "/home/gdquest/.local/share/virtualenvs/ytplaylist_converter-4rCIw-CX/lib/python3.7/site-packages/pyyoutube/api.py", line 689, in get_playlist_items
    "maxResults": min(count, limit),
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

Any idea of the cause?

**Comment by razcore-art** [comment]
Can you paste how you're using/invoking the script?

**Comment by razcore-art** [comment]
Ah wait, I know why this is happening. The `python-youtube` module I'm using isn't updated yet on `pipy` and I forgot to revert back that change.

Lines 83-85 need to be:
```py
playlists = u.get_playlist_all_items(
            api, playlist_id=args.playlist, parts=["snippet"]
        ).items
```
in your case. I'll get back to this after I finish reviewing the steering toolkit

**Comment by razcore-art** [comment]
Update:
Seems like the module author already updated the package on pypi so you can keep using `api.get_playlist_items`, you just need to update the package: `pipenv update python-youtube`. I'll change accordingly

**Comment by NathanLovato** [comment]
Thanks, could you tell me when it's ready to merge? The code is good as far as I'm concerned

**Comment by razcore-art** [comment]
Yeah, I'm doing a final pass today. I want to add some things and remove some stuff so tomorrow morning should be all good to merge.

**Comment by razcore-art** [comment]
Alright, this should be ready to go. Do some final tests if you will, check to see I didn't break anything. Updated `Pipfile`s to use latest `python-youtube` version.

**Comment by razcore-art** [comment]
Yeah so now something like this works: `pipenv run python3 ytplaylist-to-pages.py -- PLtG4P3lq8RHHAgsTl7_pd55-qHOxUBi3B PLhqJJNjsQ7KH_z21S_XeXD3Ht3WnSqW97`, i.e. multi-playlist downloaded at once. Doesn't work with `--folders` so with `--path WEBSITE --folders SOME STRUCTURE` as this is for one playlist at a time.

**Pull request merged**
