### PR TITLE
Edit the 5 habits tutorial

### PR DESCRIPTION
**Pull request by EadhCaillin**
- update the list of learnings
- remove the leftover placeholders and comments
- improve flow, expression and grammar

### CODE REVIEW

**Comment by EadhCaillin** [comment]
@NathanLovato I removed the placeholders, updated the list of learnings and changed some headings for consistency so it's worth having a look. After that, it's ready to merge.

**Comment by NathanLovato** [comment]
It's great, thanks Sally!

**Comment by NathanLovato** [comment]
Sorry, I'm not sure I get it.

Is it about creating the checklist, or are you suggesting reviewing every existing tutorial?

**Comment by EadhCaillin** [comment]
It's about creating the checklist. Not suggesting we review every existing tutorial.

**Pull request merged**
