### PR TITLE
Add picture guidelines, update checklist

### PR DESCRIPTION
**Pull request by NathanLovato**
We were missing guidelines regarding taking screenshots and using pictures, videos, and gifs in tutorials. This PR adds those guidelines.

### CODE REVIEW

**Comment by NathanLovato** [comment]
@EadhCaillin Is this something you could review and edit? There's one new guideline file and a corresponding update to the checklist.

READY FOR REVIEW

**Comment by EadhCaillin** [comment]
Sure

**Comment by EadhCaillin** [comment]
@NathanLovato Minor edits only here. The guidelines are clear. The only thing I wondered about is the very last instruction according to which a reviewer can optimize files for the writer. I find that to be a little confusing. Either we're asking them to do it and that's why we're sharing instructions, or we're saying someone else can do it for them. In my experience, ambiguity usually leads to dilution of responsibility and inaction. If you agree, please remove the last sentence in the picutres guidelines: "A reviewer or project maintainer can also do it for you." 
Otherwise, it's ready to merge.

**Comment by NathanLovato** [comment]
Done, thanks!

**Pull request merged**
