### PR TITLE
Feature/docs

### LINKED ISSUE #125: Fix up the documentation part (hugo-theme-learn)
Now that we got `docs/` working we need to organize the stuff we already have like the guidelines, guides, power sequencer documentation etc.

### PR DESCRIPTION
**Pull request by razcore-art**
- [x] moved (i.e. removed the other location - open-source folder)
  documentation from posts to docs (hugo-theme-learn)
- [x] added GDQuest logo
- [x] organized menu:
  * Guides
    + Make Games with Godot
      - Beginner Edition
      - Developer Edition
  * Guidelines
    + GDQuest's Best Practices
      - Communication
      - Godot GDScript
      - Blender Python
      - Making Videos
    + Contributing to
      - GDQuest Projects
      - Make Games with Godot Guides
  * Documentation
    + Blender Power Sequencer
      - Reference
  * Cheatsheets
    + Spacemacs
- [x] change theme variation to blue (not that we discussed about this...)
- [x] add main page menu entry for docs
- [x] write chapters & pages to tie the documents together
- ~~add a tutorial page that links to the guides as discussed with Francois on Discord~~ see #130 
- ~~review docs content to make sure all links, titles & references make sense~~ see #129 
- [x] bring back aliases
- [x] commented out the googleapi calls for getting video data
- [x] add TOC for the blender power sequencer reference (shortcuts shortcode)
- took the liberty to reorganize the main menu:
1. products
2. news
3. tuts
4. docs <-- this is new
5. about

closes #125

### CODE REVIEW

**Comment by razcore-art** [comment]
Forgot to select **DRAFT** option, but this is a **DRAFT** - some content still needs to be written, other (power sequencer) needs to be rewritten.

**Comment by razcore-art** [comment]
I think we need to change the link on the logo to point to the docs root page and not the main site as it's a bit counter-intuitive I feel. We instead can extend the menu with extra entries that go back or to other places (like the shop etc.)

**Comment by NathanLovato** [comment]
>  I think we need to change the link on the logo to point to the docs root page and not the main site

To me it's good as it is, going back to the homepage:

1. It's consistent with the rest of the website
2. The logo says GDQuest, it takes you to the GDQuest website

There should probably be two ways at least to get back to the main site. This logo _and_ a menu entry with explicit text, e.g. "Back to GDQuest.com" or "Back to the Website", something that makes sense for visitors.

**Comment by razcore-art** [comment]
The reason I said that about the logo is that there's no way to go to the main docs page except for the entry in the breadcrums at the top:
image

We then should include something in the menu as well, like "Back to GDQuest.com"

**Comment by NathanLovato** [comment]
The main thing I see at the moment is you deleted files but didn't set up aliases in the moved files' front matter. We need them, otherwise, we'll get dead links on search engines and error reports. The alias should point to the content's old location relative to the `content/` directory.

Some minor remarks:

- I'd remove the hyphens in page titles. E.g. `Godot - GDScriopt` -> `Godot GDScript`
- `GDQuest's Best Practices` -> `Best Practices`. I think our best practices are meant for everyone, and it's already on the GDQuest website.

You put your two guides in these docs. They're not really documentation to me, I think they fit the tutorials section a bit more. The reason is I think visitors may go to tutorials way more naturally than check the "docs". The tutorial section isn't incredible UX-wise but we'll get to improving it as well.

**Comment by razcore-art** [comment]
Or another idea is to have a logo for the docs: GDQuest Documents (this is how I'm renaming it by the way, instead of "Learn with GDQuest", as it's more generic). And then it makes sense to click on the logo and have it go back to the main docs index page.

**Comment by razcore-art** [comment]
> The main thing I see at the moment is you deleted files but didn't set up aliases in the moved files' front matter. We need them, otherwise, we'll get dead links on search engines and error reports. The alias should point to the content's old location relative to the `content/` directory.
> 
> Some minor remarks:
> 
> * I'd remove the hyphens in page titles. E.g. `Godot - GDScriopt` -> `Godot GDScript`
> * `GDQuest's Best Practices` -> `Best Practices`. I think our best practices are meant for everyone, and it's already on the GDQuest website.
> 
> You put your two guides in these docs. They're not really documentation to me, I think they fit the tutorials section a bit more. The reason is I think visitors may go to tutorials way more naturally than check the "docs". The tutorial section isn't incredible UX-wise but we'll get to improving it as well.

Alright, I'll keep that in mind and bring back the aliases.

**Comment by razcore-art** [comment]
I'm not entirely sure having 2 pages for the power sequencer:

- Blender Power Sequencer
  - Documentation

If we had more than documentation it would make sense to have a chapter like this but without it... don't know, it seems like an extra click to get to the actual content. I'm thinking that the Blender Power Sequencer page can be a (news) post, while the power sequencer documentation can be in the docs.

**Comment by razcore-art** [comment]
On the other hand the theme is meant to be used with chapters and that's the reason why I kept a chapter for `Cheatsheets` although there's only one in there at the moment - `Spacemacs`.

Another idea is to have:

- Documents
  - Blender Power Sequencer

So the other way around and other documents could go in there with time.

**Comment by NathanLovato** [comment]
> And then it makes sense to click on the logo and have it go back to the main docs index page.

It's true that with readthedocs the logo takes you back to the documentation's root. I don't mind the current logo going to the docs' homepage. We can treat it as its own thing.

> I'm not entirely sure having 2 pages for the power sequencer:

Documentation is a quick reference, it shouldn't be the only page. There should certainly be a page to explain what Power Sequencer is and how to use its docs. I'm also still looking to make videos for the team to talk more about workflow, e.g. cutting and trimming. So it shouldn't stay as a single page either moving forward.

The front page shouldn't be a news post as it'll sink and get lost in the website's archives. For someone exploring our website, who won't necessarily know we make different tools, they'll need a page to give them context on what power sequencer is. I should probably rework that page to fit the docs though.

**Comment by razcore-art** [comment]
So the theme can have multiple levels in the menu as you can see with the `Guidelines` where we have `Contributing to` & `Best Practices` so what about something like:

- Documents (or Docs)
  - Blender Power Sequencer
    - Entry 1
    - Entry 2
  - Godot Steering Toolkit
  - Etc.

**Comment by razcore-art** [comment]
I suppose the reason why I added "Learn Godot" to this part of the site is cause they were under `open-source` from where other documents ended up here. Didn't think about the tutorials section at the time.

**Comment by razcore-art** [comment]
So because the blender power sequencer reference document is written as a shortcode, there's no way to easily generate the TOC so we need a better way. My simple fix would be to just rewrite the Python script to generate the Markdown directly instead of the JSON data. Should be simple enough as Markdown is super basic.

**Comment by razcore-art** [comment]
In the end I rewrote `toc.html` partial, it wasn't difficult. I'm just not sure about the layout of the TOC, it's a very long list, but I don't know what other options we have.

**Comment by razcore-art** [comment]
Alright, I'm done with this @NathanLovato

**Pull request merged**
