### PR TITLE
Content/power sequencer getting started

### PR DESCRIPTION
**Pull request by johnnygossdev**
I've filled out most sections with text and instructions.

Some issues however:

1. I'd like to add .mp4s to demonstrate the features. I tried adding one but it wouldn't display on the page. I'm not sure if this is a limitation of the website or the file. I can play it just fine on my machine.
1. Setting the preview range using `Set Timeline Range` doesn't seem to work as I expect so I haven't filled that out as I'm not sure I understand it. I expect it to automatically set the range based on the strips selected but it just moves the start of the rendering range to the timeline cursor and doesn't change the end of the rendering range.

### CODE REVIEW

**Comment by NathanLovato** [comment]
> I'd like to add .mp4s to demonstrate the features

There's a shortcode for that, `video`. It takes the path to the video file and an optional width for the video player:

```{{< video "./mannequiny-idle.mp4" "720" >}}```

> Set Timeline Range

This is another feature, you need to use `Preview to Selection`

**Comment by NathanLovato** [comment]
I'll let you finish the guide, tell me when it's time to review and do an editing pass.

**Comment by johnnygossdev** [comment]
I've added the videos and finished of the remaining sections. It's ready for an edit.

**Comment by NathanLovato** [comment]
Good job, it's clear and to the point!

**Pull request merged**
