### PR TITLE
Fix/top nav hover

### PR DESCRIPTION
**Pull request by gdomaradzki**
solves #156 

I made so the hover effect is a transition from white to `$color-accent-opt-base`, plus also removed a huge `line-height` that was influencing the hover range.

### CODE REVIEW

**Comment by NathanLovato** [comment]
Could you create a branch for each PR? Otherwise, when you add commits, they all get added to every PR you opened at the same time.

**Comment by gdomaradzki** [comment]
> Could you create a branch for each PR? Otherwise, when you add commits, they all get added to every PR you opened at the same time.

Yeah, the first one I pushed directly to master, this one was in another branch, want me to close this and re-do it without having track of the previous commits?

**Comment by NathanLovato** [comment]
Yeah, I can't cherry-pick one of the commits, I'll rebase and merge manually

**Comment by gdomaradzki** [comment]
> Yeah, I can't cherry-pick one of the commits, I'll rebase and merge manually

Sorry, I imagined this would cause trouble. Will prevent it on future PRs.

**Comment by NathanLovato** [comment]
No worries, I merged manually in 
4293e5b27fcd4c0f92dd30a87f595e5b5978838c and
ea4215a9e4cb4e4634d268561ff79836c925771c

**Comment by NathanLovato** [comment]
Thanks!

**Pull request closed without merging**
