### PR TITLE
placeholder for lazy-load yt videos

### PR DESCRIPTION
**Pull request by marianka6252**
To the project was added placeholder for youtube videos to lazy-load them. 
Issue #227

### CODE REVIEW

**Comment by NathanLovato** [comment]
Thanks, it works, but the code style doesn't follow the website's guidelines. It would take a while to go put review comments. May I refactor your code directly instead?

**Comment by marianka6252** [comment]
Sure.

**Comment by NathanLovato** [comment]
Done, you can check this commit for the changes: https://github.com/GDQuest/website/pull/237/commits/4cee28a46e3023af7341fcc03014392ef9b404cc

Your code would be duplicated and re-run for each youtube video on a given page, this is now fixed.

**Comment by NathanLovato** [comment]
Thanks!

**Pull request merged**
